### ISSUE TITLE
Como listar o ultimo registro de uma tabela?

### ISSUE THREAD

**Issue by wiltonwilldepaulo** [bittencourtthulio/SimpleORM#21]
Como listar o ultimo registro de uma tabela?

Estou fazendo uma venda, na hora de salvar os itens da venda, como saber o código da ultima venda salva. Para inserir aos itens da venda?

**Comment by reinaldoacdc** [comment]
Veja o commit: https://github.com/bittencourtthulio/SimpleORM/commit/1e3290abf6b510ae30d905e5563d4a081474894c

SimpleDAO.LastRecord
