### ISSUE TITLE
LastRecord e LastID - Não está adaptado para MySQL

### ISSUE THREAD

**Issue by jperim** [bittencourtthulio/SimpleORM#26]
function TSimpleSQL<T>.LastID(var aSQL: String): iSimpleSQL<T>;
function TSimpleSQL<T>.LastRecord(var aSQL: String): iSimpleSQL<T>;

select FIRST 1 não existe no MySQL, q deveria ser no final colocar LIMIT 1.

Eu sou programador q ainda estou aprendendo as boas praticas MVC etc.. então não muito indicador pra dar um boa solução para este caso. Só estou mostrando algo q possa ser melhorado por alguém.
Pra mim, eu fiz um overload dessas 2 functions para pode usá-la no meu sistema.

**Comment by alepmedeiros** [comment]
tranquilo meu amigo, iremos verificar

**Comment by alepmedeiros** [comment]
issue finalizado
