### ISSUE TITLE
Delphi Tokyo 10.2 -  SimpleRTTI.pas(233): E2003 Undeclared identifier: 'tkMRecord'

### ISSUE THREAD

**Issue by maiconsaraiva** [bittencourtthulio/SimpleORM#32]
https://github.com/bittencourtthulio/SimpleORM/blob/1a1b3800bc597928ee46001429b6f420b56b80b9/SimpleRTTI.pas#L238

Olá pessoal, baixei o SimpleORM para usar em um pequeno projeto.
Uso Delphi Tokyo 10.2, e está acusando erro na linha 238 do arquivo SimpleRTTI.pas ao tentar compilar.

Erro:
[dcc32 Error] SimpleRTTI.pas(233): E2003 Undeclared identifier: 'tkMRecord'

Aparentemente, na versão Tokyo 10.2, esse TypeKind ainda não foi implementado.
No arquivo System.pas ele existe, mas está comentado.

Linha 1418 do System.pas:
```
   // Sync with compiler internals
  TTypeKind = (tkUnknown, tkInteger, tkChar, tkEnumeration, tkFloat,
    tkString, tkSet, tkClass, tkMethod, tkWChar, tkLString, tkWString,
    tkVariant, tkArray, tkRecord, tkInterface, tkInt64, tkDynArray, tkUString,
    tkClassRef, tkPointer, tkProcedure {, tkMRecord});
```

**Comment by bittencourtthulio** [comment]
Resolvido
