### ISSUE TITLE
Conflito entre o SimpleDAO e o Router4D em projeto VCL no Delphi Rio

### ISSUE THREAD

**Issue by isaqueribeiro** [bittencourtthulio/SimpleORM#33]
Boa noite, pessoal.
Postei esse problema no grupo do Telegram, mas estou postando aqui também.

Estou trabalhando em um projeto VCL, aplicados as técnicas do curso DDI e DDE. Com isso passei a utilizar nesse projeto os componentes  SimpleORM e o Router4D. Mas todas as vezes que adiciono a unit SimpleDAO  no meu projeto, a minha classe "_Routers" deixar de registrar as rotas e minhas pages. Com isso aparece o erro "Classe TViewHome not found".

O estranho é que a classe está registrada e o projeto está compilando normalmente, mas quando ele é instanciado e o TRouter4D tenta carregar a "ViewHome", o erro é apresentado. E quando eu removo a unit SimpleDAO, o projeto volta a funcionar normalmente.

Este é o link dos fontes do projeto para que este caso seja analisado pela equipe:
https://drive.google.com/file/d/1myXpPrJQNxhCbsOWS0KgkKkOHVXV47B4/view?usp=sharing

**Comment by reinaldoacdc** [comment]
Baixei aqui e identifiquei onde estava dando o problema. 

Tinha um uses dando erro, se retirar ele já vai conseguir rodar aí. 
Subi um PR já, ai só comparar.

**Comment by bittencourtthulio** [comment]
Resolvido

**Comment by carloshteles** [comment]
Boa noite... estou com o mesmo problema porém no FMX, qual seria a solução? qual USE eu preciso retirar?

Grato
