### ISSUE TITLE
Ajuste compilação FMX classe SimpleRTTI

### ISSUE THREAD

**Issue by maicorheinheimer** [bittencourtthulio/SimpleORM#41]
Ajuste de diretiva de compilação para FMX na classe SimpleRTTI segue em anexo.

implementation

uses
  SimpleAttributes,

  {$IFNDEF CONSOLE}
    {$IFDEF FMX}
    FMX.Graphics,
    {$ELSE}
    Vcl.ComCtrls,
    Vcl.Graphics,
    {$ENDIF}
  {$ENDIF}
  Variants,
  SimpleRTTIHelper,
  System.UITypes;

[SimpleRTTI.zip](https://github.com/bittencourtthulio/SimpleORM/files/6519595/SimpleRTTI.zip)

**Comment by alepmedeiros** [comment]
opa meu amigo, para sua contribuição é necessário um pull request
